kubectl delete crd accesspolicies.cloud.grafana.crossplane.io 
kubectl delete crd accesspolicyrotatingtokens.cloud.grafana.crossplane.io 
kubectl delete crd accesspolicytokens.cloud.grafana.crossplane.io 
kubectl delete crd alertenrichmentv1beta1s.alerting.grafana.crossplane.io 
kubectl delete crd alertrulev0alpha1s.alerting.grafana.crossplane.io 
kubectl delete crd alerts.ml.grafana.crossplane.io 
kubectl delete crd annotations.oss.grafana.crossplane.io 
kubectl delete crd appo11yconfigv1alpha1s.cloud.grafana.crossplane.io 
kubectl delete crd apps.frontendobservability.grafana.crossplane.io 
kubectl delete crd awsaccounts.cloudprovider.grafana.crossplane.io 
kubectl delete crd awscloudwatchscrapejobs.cloudprovider.grafana.crossplane.io 
kubectl delete crd awsresourcemetadatascrapejobs.cloudprovider.grafana.crossplane.io 
kubectl delete crd azurecredentials.cloudprovider.grafana.crossplane.io 
kubectl delete crd checkalerts.sm.grafana.crossplane.io 
kubectl delete crd checks.sm.grafana.crossplane.io 
kubectl delete crd collectors.fleetmanagement.grafana.crossplane.io 
kubectl delete crd connectionv0alpha1s.oss.grafana.crossplane.io 
kubectl delete crd contactpoints.alerting.grafana.crossplane.io 
kubectl delete crd custommodelrules.asserts.grafana.crossplane.io 
kubectl delete crd dashboardpermissionitems.oss.grafana.crossplane.io 
kubectl delete crd dashboardpermissions.oss.grafana.crossplane.io 
kubectl delete crd dashboardpublics.oss.grafana.crossplane.io 
kubectl delete crd dashboardv1beta1s.oss.grafana.crossplane.io 
kubectl delete crd dashboardv2beta1s.oss.grafana.crossplane.io 
kubectl delete crd dashboardv2s.oss.grafana.crossplane.io 
kubectl delete crd datasourcecacheconfigs.enterprise.grafana.crossplane.io 
kubectl delete crd datasourceconfiglbacrules.enterprise.grafana.crossplane.io 
kubectl delete crd datasourceconfigs.oss.grafana.crossplane.io 
kubectl delete crd datasourcepermissionitems.enterprise.grafana.crossplane.io 
kubectl delete crd datasourcepermissions.enterprise.grafana.crossplane.io 
kubectl delete crd escalationchains.oncall.grafana.crossplane.io 
kubectl delete crd escalations.oncall.grafana.crossplane.io 
kubectl delete crd folderpermissionitems.oss.grafana.crossplane.io 
kubectl delete crd folderpermissions.oss.grafana.crossplane.io 
kubectl delete crd holidays.ml.grafana.crossplane.io 
kubectl delete crd inhibitionrulev1beta1s.alerting.grafana.crossplane.io 
kubectl delete crd installations.k6.grafana.crossplane.io 
kubectl delete crd installations.sm.grafana.crossplane.io 
kubectl delete crd integrations.oncall.grafana.crossplane.io 
kubectl delete crd jobs.ml.grafana.crossplane.io 
kubectl delete crd k8so11yconfigv1alpha1s.cloud.grafana.crossplane.io 
kubectl delete crd keeperactivationv1beta1s.enterprise.grafana.crossplane.io 
kubectl delete crd keeperv1beta1s.enterprise.grafana.crossplane.io 
kubectl delete crd librarypanels.oss.grafana.crossplane.io 
kubectl delete crd loadtests.k6.grafana.crossplane.io 
kubectl delete crd logconfigs.asserts.grafana.crossplane.io 
kubectl delete crd messagetemplates.alerting.grafana.crossplane.io 
kubectl delete crd metricsendpointscrapejobs.connections.grafana.crossplane.io 
kubectl delete crd mutetimings.alerting.grafana.crossplane.io 
kubectl delete crd notificationalertsconfigs.asserts.grafana.crossplane.io 
kubectl delete crd notificationpolicies.alerting.grafana.crossplane.io 
kubectl delete crd oncallshifts.oncall.grafana.crossplane.io 
kubectl delete crd organizationpreferences.oss.grafana.crossplane.io 
kubectl delete crd organizations.oss.grafana.crossplane.io 
kubectl delete crd orgmembers.cloud.grafana.crossplane.io 
kubectl delete crd outgoingwebhooks.oncall.grafana.crossplane.io 
kubectl delete crd outlierdetectors.ml.grafana.crossplane.io 
kubectl delete crd pipelines.fleetmanagement.grafana.crossplane.io 
kubectl delete crd playlists.oss.grafana.crossplane.io 
kubectl delete crd playlistv0alpha1s.oss.grafana.crossplane.io 
kubectl delete crd playlistv1s.oss.grafana.crossplane.io 
kubectl delete crd plugininstallations.cloud.grafana.crossplane.io 
kubectl delete crd privatedatasourceconnectnetworks.cloud.grafana.crossplane.io 
kubectl delete crd privatedatasourceconnectnetworktokens.cloud.grafana.crossplane.io 
kubectl delete crd probes.sm.grafana.crossplane.io 
kubectl delete crd profileconfigs.asserts.grafana.crossplane.io 
kubectl delete crd projectallowedloadzones.k6.grafana.crossplane.io 
kubectl delete crd projectlimits.k6.grafana.crossplane.io 
kubectl delete crd projects.k6.grafana.crossplane.io 
kubectl delete crd promrulefiles.asserts.grafana.crossplane.io 
kubectl delete crd recordingrulev0alpha1s.alerting.grafana.crossplane.io 
kubectl delete crd reports.enterprise.grafana.crossplane.io 
kubectl delete crd repositoryv0alpha1s.oss.grafana.crossplane.io 
kubectl delete crd resources.oss.grafana.crossplane.io 
kubectl delete crd roleassignmentitems.enterprise.grafana.crossplane.io 
kubectl delete crd roleassignments.enterprise.grafana.crossplane.io 
kubectl delete crd roles.enterprise.grafana.crossplane.io 
kubectl delete crd routes.oncall.grafana.crossplane.io 
kubectl delete crd rulegroups.alerting.grafana.crossplane.io 
kubectl delete crd schedules.k6.grafana.crossplane.io 
kubectl delete crd schedules.oncall.grafana.crossplane.io 
kubectl delete crd scimconfigs.enterprise.grafana.crossplane.io 
kubectl delete crd securevaluev1beta1s.enterprise.grafana.crossplane.io 
kubectl delete crd serviceaccountpermissionitems.oss.grafana.crossplane.io 
kubectl delete crd serviceaccountpermissions.oss.grafana.crossplane.io 
kubectl delete crd serviceaccountrotatingtokens.oss.grafana.crossplane.io 
kubectl delete crd serviceaccounts.oss.grafana.crossplane.io 
kubectl delete crd serviceaccounttokens.oss.grafana.crossplane.io 
kubectl delete crd slos.slo.grafana.crossplane.io 
kubectl delete crd ssosettings.oss.grafana.crossplane.io 
kubectl delete crd stacks.asserts.grafana.crossplane.io 
kubectl delete crd stacks.cloud.grafana.crossplane.io 
kubectl delete crd stackserviceaccountrotatingtokens.cloud.grafana.crossplane.io 
kubectl delete crd stackserviceaccounts.cloud.grafana.crossplane.io 
kubectl delete crd stackserviceaccounttokens.cloud.grafana.crossplane.io 
kubectl delete crd suppressedassertionsconfigs.asserts.grafana.crossplane.io 
kubectl delete crd teamexternalgroups.enterprise.grafana.crossplane.io 
kubectl delete crd teams.oss.grafana.crossplane.io 
kubectl delete crd thresholds.asserts.grafana.crossplane.io 
kubectl delete crd traceconfigs.asserts.grafana.crossplane.io 
kubectl delete crd usernotificationrules.oncall.grafana.crossplane.io 
kubectl delete crd users.oss.grafana.crossplane.io 

