# .\Provider-Cleanup.ps1 -provider_keyword "grafana.crossplane.io" -mrap_name "provider-grafana"
param (
    [string]$provider_keyword,
    [string]$mrap_name
)

# Error handling for missing arguments
if (-not $provider_keyword) {
    Write-Host "Please provide a provider suffix as an argument, e.g. -provider_keyword 'grafana'."
    exit 1
}

if (-not $mrap_name) {
    Write-Host "Please provide a mrap name as an argument, e.g. -mrap_name 'provider-grafana'."
    exit 1
}

Write-Output "Checking CRD cleanup for provider suffix: $provider_keyword"

$crdsInUse = @()

# Read provider usage information from the result file generated by Provider-Usage-Export.ps1
$usage_file = "provider_usage_$provider_keyword.json"
if (Test-Path $usage_file) {
    $usage_data = Get-Content $usage_file | ConvertFrom-Json
    $crdsInUse += $usage_data
} else {
    Write-Output "No usage data file found for provider suffix '$provider_keyword'. Please run Provider-Usage-Export.ps1 first to generate the usage data."
    exit 1
}

$mrap = kubectl get mrap $mrap_name -o json | ConvertFrom-Json
$crdsInUse += $mrap.spec.activate

$crdsInUse | ConvertTo-Json -Depth 100 | Out-File -FilePath "provider_usage_${provider_keyword}-merged.json" -Encoding utf8


$willBeDeleted = @()

kubectl get crds -o name | Where-Object { $_ -like "*$provider_keyword*" } | ForEach-Object {
    #Write-Output "Processing CRD: $_"

    # trim until '/' to get the CRD name
    $crdName = $_.Split('/')[1]
    #Write-Output "CRD name: $crdName"
    #$crds = kubectl get $($crdName) --all-namespaces -o json | ConvertFrom-Json

    if ($crdsInUse -notcontains $crdName) {
        Write-Output "CRD '$crdName' is not in use and can be deleted."
        $willBeDeleted += $crdName
        # Uncomment the line below to actually delete the CRD
        # kubectl delete crd $crdName
    } else {
        Write-Output "CRD '$crdName' is in use and cannot be deleted."
    }

} 

# Write Powershell script
$scriptFile = "delete-${mrap_name}-crds.ps1"

$scriptContents = ''

foreach ($item in $willBeDeleted) {
    # append "kubectl delete crd $item \n" to the script contents
    $scriptContents += "kubectl delete mrd $item `n"    
    $scriptContents += "kubectl delete crd $item `n"    
    # $scriptContents += "kubectl delete crd $item `n"    
}

#foreach ($item in $willBeDeleted) {
#    $scriptContents += "kubectl delete crd $item \n"    
#}

Write-Output "$scriptContents"


$scriptContents | Out-File -FilePath $scriptFile -Encoding utf8

