apiVersion: v1
data:
  credentials: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lJeE1qTTBOVFkzT0Rrd0lpd2libUZ0WlNJNklrcHZhRzRnUkc5bElpd2lZV1J0YVc0aU9uUnlkV1VzSW1saGRDSTZNVFV4TmpJek9UQXlNbjAuS01VRnNJRFRuRm15RzNuTWlHTTZIOUZORlVST2Yzd2g3U21xSnAtUVYzMA==
kind: Secret
metadata:
  name: grafana-secret
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/tracking-id: crossplane-providers:/Secret:crossplane-system/grafana-secret
type: Opaque  