apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-core
  namespace: argo-cd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-diff-preview/watch-pattern: |
      dev/cert-manager/core/values.yaml
spec:
  project: platform-system
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.15.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/dev/cert-manager/core/values.yaml
    - repoURL: https://github.com/nsalexamy/kargo-playground-infra.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "control-plane")
        - .webhooks[].namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")
