apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-system
  namespace: argo-cd
spec:
  description: Argo CD project using SSH-based Git repo

  # Important: use the SSH-formatted Git URL
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'