args:
- --debug
replicas: 1

provider:
  defaultActivations: []

resourcesCrossplane:
  limits:
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi
resourcesRBACManager:
  requests:
    memory: 128Mi

